all:
  # Add common SSH variables to disable host key checking and send remote host keys to /dev/null
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  children:
    web:
      hosts:
        server-one:
          # Server host name
          ansible_host: ec2-52-27-79-236.us-west-2.compute.amazonaws.com
          # User to connect over SSH with
          ansible_user: ubuntu
          # Private key file to use for SSH authentication
          ansible_ssh_private_key_file: ~/.ssh/aws
          
        server-two:
          # Server host name
          ansible_host: ec2-34-220-217-170.us-west-2.compute.amazonaws.com
          # User to connect over SSH with
          ansible_user: ubuntu
          # Private key file to use for SSH authentication
          ansible_ssh_private_key_file: ~/.ssh/aws
